server:
  port: 8080
  servlet:
    context-path: /snaplinks-api/v1

spring:
  application:
    name: SnapLinks
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/snaplinks
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ef6f933b00ec074372d7cb77c42cff77b5198c0cbc32ed8b9a8d301043b7e946
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
